[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
filterwarnings =
    ignore:.*Query.get\(\).*:DeprecationWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning
